django_level_four/learning_templates/basicap/urls.py
from django.conf.urls import url
from basicap import views

app_name = 'basicap'

urlpatterns = [
    url(r'^relative/$',views.relative,name='relative'),
    url(r'^other/$',views.other,name='other')
]

django_level_two/ProTwo/ProTwo/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from appTwo import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('appTwo.urls')),
]

first_project/first_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from first_app import views

urlpatterns = [
    url(r'^first_app',include('first_app.urls')),
    url(r'^$',views.index,name='index'),
    url(r'^admin/', admin.site.urls),
]

two_project/two_app/urls.py
from django.conf.urls import url
from two_app import views

urlpatterns = [
    url(r'^$',views.help,name='index')
]

two_project/two_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from two_app import views

urlpatterns = [
    url(r'^help',include('two_app.urls')),
    url(r'^$', views.index,name='index'),
    url(r'^admin/', admin.site.urls),
]

django_level_four/learning_templates/basicap/models.py
from django.db import models

# Create your models here.

django_level_four/learning_templates/basicap/views.py
from django.shortcuts import render

def index(request):
    context={'text':'My name is Asli','istenmeyen':'beni değil onu kes'}
    return render(request,'basicap/index.html',context)
def other(request):
    return render(request,'basicap/other.html')
def relative(request):
    return render(request,'basicap/relative_url_templates.html')

django_level_four/learning_templates/templates/basicap/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" >
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Aslılılılı</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'index'%}">Home</a></li>
        <li><a href="{% url 'basicap:other'%}">Other</a></li>
          <li><a href="{% url 'admin:index'%}">Admin</a></li>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
{% block body_block %}
{% endblock %}
<footer style="background-color:#f8f8f8">
<p class="container">Tags:
    <a href="#"><span class="label label-info">Snipp</span></a>
	<a href="#"><span class="label label-info">Bootstrap</span></a>
	<a href="#"><span class="label label-info">UI</span></a>
	<a href="#"><span class="label label-info">growth</span></a>
	| <i class="icon-user"></i> <a href="#">Admin</a>
	| <i class="icon-calendar"></i> Sept 16th, 2012 at 4:20 pm
 	| <i class="icon-comment"></i> <a href="#">3 Comments</a>
   	| <i class="icon-share"></i> <a href="#">39 Shares</a>
</p>
</footer>
</body>
</html>

django_level_four/learning_templates/templates/basicap/index.html
<!DOCTYPE html>

{% extends "basicap/base.html" %}
<div class="container">

    {% block body_block %}
    <h1>Welcome to index</h1>
    {{text|upper}}
    {{istenmeyen|cut:'kes'}}
    {% endblock %}
</div>

django_level_four/learning_templates/templates/basicap/other.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="container">
    <h1>Welcome to other</h1>
</div>
</body>
</html>

django_level_four/learning_templates/templates/basicap/relative_url_templates.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="container">
    <h1>Welcome to relative</h1>
    <a href="{% url 'basicap:other' %}">Go Other</a>
</div>
</body>
</html>